/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dewantaradb;

/**
 *
 * @author MogaTaufiq
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Dewantara extends javax.swing.JFrame {
    private static final String JDBC_URL = "jdbc:sqlserver://localhost:1433;encrypt=true; trustServerCertificate=true;databaseName=Dewantara";
    private static final String USER = "sa";
    private static final String PASSWORD = "Strong.Pwd-123"; 
    
    DetailDewantara DetailFrame = new DetailDewantara();    
    DetailOrangTua DetailOrtu = new DetailOrangTua();
    DetailTransaksi DetailTransaksi = new DetailTransaksi();
    EditSiswa EditSiswa = new EditSiswa();
    EditOrtu EditOrtu = new EditOrtu();
    NewSIswa createSiswa = new NewSIswa();
    NewTransaksi createTransaksi = new NewTransaksi();
    
    public void setModel(DefaultTableModel model) {
        table.setModel(model);
    }


    /**
     * Creates new form Dewantara
     */
    public Dewantara() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        edit = new javax.swing.JButton();
        view = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        create = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(210, 227, 200));

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(134, 156, 109));
        jLabel1.setText("Dewantara");

        search.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        search.setText("search here");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("SF Pro Display", 1, 10)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Siswa", "Orangtua", "Transaksi" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        table.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Gender"
            }
        ));
        jScrollPane1.setViewportView(table);

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(300, 300, 300))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 114, Short.MAX_VALUE)
                    .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(create)
                        .addGap(18, 18, 18)
                        .addComponent(view)
                        .addGap(18, 18, 18)
                        .addComponent(delete)
                        .addGap(18, 18, 18)
                        .addComponent(edit)
                        .addGap(18, 18, 18)
                        .addComponent(refresh)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String keyword = search.getText();
        
        String selectedOption = jComboBox1.getSelectedItem().toString();
        switch (selectedOption) {
            case "Siswa" -> {
             searchAndDisplaySiswa(keyword);
        }
            case "Orangtua" -> {
             searchAndDisplayOrtu(keyword);
        }
            case "Transaksi" -> {
               
            
          }
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        String selectedOption = jComboBox1.getSelectedItem().toString();
        switch (selectedOption) {
            case "Siswa" -> {
            int selectedRow = table.getSelectedRow();

            if (selectedRow != -1) {
            String nis = table.getValueAt(selectedRow, 0).toString();

            fetchDataFromSiswaAndDisplayInEditFrame(nis);

            EditSiswa.setVisible(true);
            } else {
            JOptionPane.showMessageDialog(this, "Pilih baris untuk diedit", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        }
            case "Orangtua" -> {
            int selectedRow = table.getSelectedRow();

            if (selectedRow != -1) {
            int id = (int) table.getValueAt(selectedRow, 0);

            fetchDataFromOrtuAndDisplayInEditFrame(id);

            EditOrtu.setVisible(true);
            } else {
            JOptionPane.showMessageDialog(this, "Pilih baris untuk diedit", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        }
            case "Transaksi" -> {
                JOptionPane.showMessageDialog(this, "Tidak bisa edit Transaksi", "Peringatan", JOptionPane.WARNING_MESSAGE);
            
          }
        }
        
        
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String selectedOption = jComboBox1.getSelectedItem().toString();
        switch (selectedOption) {
            case "Siswa" -> {
            int selectedRow = table.getSelectedRow();

            if (selectedRow != -1) {
                String nisToDelete = table.getValueAt(selectedRow, 0).toString();

                deleteSiswaFromDatabase(nisToDelete);
                ((DefaultTableModel) table.getModel()).removeRow(selectedRow);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih baris untuk dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        }
            case "Orangtua" -> {
            int selectedRow = table.getSelectedRow();

            if (selectedRow != -1) {
                int idToDelete = (int) table.getValueAt(selectedRow, 0);

                deleteOrangTuaFromDatabase(idToDelete);
                ((DefaultTableModel) table.getModel()).removeRow(selectedRow);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih baris untuk dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        }
            case "Transaksi" -> {
            int selectedRow = table.getSelectedRow();
            if (selectedRow != -1) {
                int noTransaksi = (int) table.getValueAt(selectedRow, 0);

                deleteTransaksiFromDatabase(noTransaksi);
                ((DefaultTableModel) table.getModel()).removeRow(selectedRow);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih baris untuk dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
          }
        }
        
    }//GEN-LAST:event_deleteActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        String selectedOption = jComboBox1.getSelectedItem().toString();
        switch (selectedOption) {
            case "Siswa" -> {
            int selectedRow = table.getSelectedRow();

            if (selectedRow != -1) {
            String nis = table.getValueAt(selectedRow, 0).toString();

            fetchDataFromSiswaAndDisplayInDetailFrame(nis);

            DetailFrame.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih baris untuk dilihat", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        }
            case "Orangtua" -> {
            int selectedRow = table.getSelectedRow();

            if (selectedRow != -1) {
            int id = (int) table.getValueAt(selectedRow, 0);

            fetchDataFromOrtuAndDisplayInDetailFrame(id);

            DetailOrtu.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih baris untuk dilihat", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        }
            case "Transaksi" -> {
            int selectedRow = table.getSelectedRow();

            if (selectedRow != -1) {
            int noTransaksi = (int) table.getValueAt(selectedRow, 0);

            fetchKeteranganTransaksiAndDisplayInDetailTransaksiFrame(noTransaksi);

            DetailTransaksi.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih baris untuk dilihat", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
          }
        }
        
    }//GEN-LAST:event_viewActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    String selectedOption = jComboBox1.getSelectedItem().toString();

        switch (selectedOption) {
            case "Siswa" -> {
                try {
                displaySiswaData();
                refresh.setVisible(true);
                edit.setVisible(true);
                create.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Dewantara.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            case "Orangtua" -> {
                try {
                displayOrangTuaData();
                create.setVisible(false);
                refresh.setVisible(true);
                edit.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Dewantara.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            case "Transaksi" -> {
                try {
                displayTransaksiData();
                create.setVisible(true);
                refresh.setVisible(true);
                edit.setVisible(false);
                } catch (SQLException ex) {
                    Logger.getLogger(Dewantara.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        String selectedOption = jComboBox1.getSelectedItem().toString();

        switch (selectedOption) {
            case "Siswa" -> {
            try {
                displaySiswaData();
            } catch (SQLException ex) {
                Logger.getLogger(Dewantara.class.getName()).log(Level.SEVERE, null, ex);
            }
            }   
            case "Orangtua" -> {
                try {
                displayOrangTuaData();
                } catch (SQLException ex) {
                    Logger.getLogger(Dewantara.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            case "Transaksi" -> {
                try {
                displayTransaksiData();
                } catch (SQLException ex) {
                    Logger.getLogger(Dewantara.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
      }
        
    }//GEN-LAST:event_refreshActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        String selectedOption = jComboBox1.getSelectedItem().toString();

        switch (selectedOption) {
            case "Siswa" -> {
               createSiswa.setVisible(true);
            }   
            case "Orangtua" -> {
            }
            case "Transaksi" -> {
                createTransaksi.setVisible(true);
            }
      }
        
    }//GEN-LAST:event_createActionPerformed

    /**
     * @param args the command line arguments
     */
    class NonEditableTableModel extends DefaultTableModel {
    @Override
    public boolean isCellEditable(int row, int column) {
        // Tidak mengizinkan pengeditan sel
        return false;
    }
}
    
    private void searchAndDisplaySiswa(String keyword) {
    // Lakukan koneksi ke database dan eksekusi query pencarian
    try (Connection connection = DriverManager.getConnection(JDBC_URL, USER, PASSWORD)) {
        String query = "SELECT NIS, Nama, Gender FROM Siswa WHERE Nama LIKE ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setString(1, "%" + keyword + "%");

            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
                tableModel.setRowCount(0); 

                while (resultSet.next()) {
                    String nis = resultSet.getString("NIS");
                    String nama = resultSet.getString("Nama");
                    String gender = resultSet.getString("Gender");

                    Object[] rowData = {nis, nama, gender};
                    tableModel.addRow(rowData);
                }
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Handle SQL exception (e.g., display an error message)
    }
}
    
    private void searchAndDisplayOrtu(String keyword) {
    // Lakukan koneksi ke database dan eksekusi query pencarian
    try (Connection connection = DriverManager.getConnection(JDBC_URL, USER, PASSWORD)) {
        String query = "SELECT OrangTua.ID, OrangTua.NIS, Siswa.Nama AS NamaSiswa, OrangTua.NamaAyah, OrangTua.NamaIbu " +
                       "FROM OrangTua " +
                       "JOIN Siswa ON OrangTua.NIS = Siswa.NIS WHERE OrangTua.NamaAyah LIKE ? OR OrangTua.NamaIbu LIKE ?";        
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            String keywordPattern = "%" + keyword + "%";
            preparedStatement.setString(1, keywordPattern);
            preparedStatement.setString(2, keywordPattern);

            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
                tableModel.setRowCount(0); 

                while (resultSet.next()) {
                    int id = resultSet.getInt("ID");
                    String namaSiswa = resultSet.getString("NamaSiswa");
                    String namaAyah = resultSet.getString("NamaAyah");
                    String namaIbu = resultSet.getString("NamaIbu");

                    Object[] rowData = {id, namaSiswa, namaAyah, namaIbu};
                    tableModel.addRow(rowData);
                }
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Handle SQL exception (e.g., display an error message)
    }
}

    
    private void displaySiswaData() throws SQLException {
    try (Connection connection = DriverManager.getConnection(JDBC_URL, USER, PASSWORD)) {
        String query = "SELECT * FROM Siswa";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query);
             ResultSet resultSet = preparedStatement.executeQuery()) {

            DefaultTableModel model = new NonEditableTableModel();
            model.addColumn("NIS");
            model.addColumn("Nama");
            model.addColumn("Gender");

            while (resultSet.next()) {
                Object[] row = {
                        resultSet.getString("NIS"),
                        resultSet.getString("Nama"),
                        resultSet.getString("Gender"),
                };
                model.addRow(row);
            }

            table.setModel(model);

        } catch (SQLException ex) {
            ex.printStackTrace();
            // Handle SQL exception (e.g., display an error message)
        }
    }
    }
    
    private void displayOrangTuaData() throws SQLException {
 try (Connection connection = DriverManager.getConnection(JDBC_URL, USER, PASSWORD)) {
   String query = "SELECT OrangTua.ID, OrangTua.NIS, Siswa.Nama AS NamaSiswa, OrangTua.NamaAyah, OrangTua.NamaIbu " +
                       "FROM OrangTua " +
                       "JOIN Siswa ON OrangTua.NIS = Siswa.NIS";
    try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
        try (ResultSet resultSet = preparedStatement.executeQuery()) {

            DefaultTableModel model = new NonEditableTableModel();
            model.addColumn("ID");
            model.addColumn("Nama Siswa");
            model.addColumn("Nama Ayah");
            model.addColumn("Nama Ibu");

            while (resultSet.next()) {
                Object[] row = {
                        resultSet.getInt("ID"),
                        resultSet.getString("NamaSiswa"),
                        resultSet.getString("NamaAyah"),
                        resultSet.getString("NamaIbu"),
                };
                model.addRow(row);
            }

            table.setModel(model);

        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Handle SQL exception (e.g., display an error message)
    }
    }
    }
    
    private void displayTransaksiData() throws SQLException {
    try (Connection connection = DriverManager.getConnection(JDBC_URL, USER, PASSWORD)) {
        String query = "SELECT Transaksi.NIS, Siswa.Nama AS NamaSiswa, Transaksi.NomorTransaksi, Transaksi.JumlahUang " +
                       "FROM Transaksi " +
                       "JOIN Siswa ON Transaksi.NIS = Siswa.NIS";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query);
             ResultSet resultSet = preparedStatement.executeQuery()) {

            DefaultTableModel model = new NonEditableTableModel();
            model.addColumn("Nomor Transaksi");
            model.addColumn("Nama Siswa");
            model.addColumn("Jumlah Uang");

            while (resultSet.next()) {
                Object[] row = {
                        resultSet.getInt("NomorTransaksi"),
                        resultSet.getString("NamaSiswa"),
                        resultSet.getBigDecimal("JumlahUang"),
                };
                model.addRow(row);
            }

            table.setModel(model);

        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Handle SQL exception (e.g., display an error message)
    }
}

    
    private void fetchDataFromSiswaAndDisplayInDetailFrame(String nis) {
    try (Connection connection = DriverManager.getConnection(JDBC_URL, USER, PASSWORD)) {
        String query = "SELECT * FROM Siswa WHERE NIS = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setString(1, nis);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    Date tanggalLahir = resultSet.getDate("TanggalLahir");
                    // Assuming DetailFrame has methods to set all the data
                    DetailFrame.setNIS(resultSet.getString("NIS"));
                    DetailFrame.setNama(resultSet.getString("Nama"));
                    DetailFrame.setGender(resultSet.getString("Gender"));
                    DetailFrame.setTempat(resultSet.getString("Tempat"));
                    DetailFrame.setTanggalLahir(tanggalLahir);
                    DetailFrame.setAlamat(resultSet.getString("Alamat"));
                    DetailFrame.setNoTelp(resultSet.getString("noTelp"));
                    // Set other details as needed
                }
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Handle SQL exception (e.g., display an error message)
    }
}
    
    private void fetchDataFromOrtuAndDisplayInDetailFrame(int id) {
    try (Connection connection = DriverManager.getConnection(JDBC_URL, USER, PASSWORD)) {
        String query = "SELECT OrangTua.*, Siswa.Nama AS NamaSiswa " +
               "FROM OrangTua " +
               "JOIN Siswa ON OrangTua.NIS = Siswa.NIS " +
               "WHERE OrangTua.ID = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setInt(1, id);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    DetailOrtu.setNamaAyah(resultSet.getString("NamaAyah"));                    
                    DetailOrtu.setKerjaAyah(resultSet.getString("KerjaAyah"));
                    DetailOrtu.setNamaIbu(resultSet.getString("NamaIbu"));
                    DetailOrtu.setKerjaIbu(resultSet.getString("KerjaIbu"));
                    DetailOrtu.setNamaSiswa(resultSet.getString("NamaSiswa"));

                }
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Handle SQL exception (e.g., display an error message)
    }
}
    
    private void fetchKeteranganTransaksiAndDisplayInDetailTransaksiFrame(int nomorTransaksi) {
    try (Connection connection = DriverManager.getConnection(JDBC_URL, USER, PASSWORD)) {
        String query = "SELECT * FROM KeteranganTransaksi WHERE NomorTransaksi = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setInt(1, nomorTransaksi);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("ID");
                model.addColumn("NomorTransaksi");
                model.addColumn("JumlahUang");
                model.addColumn("Keterangan");

                while (resultSet.next()) {
                    Object[] row = {
                            resultSet.getInt("ID"),
                            resultSet.getInt("NomorTransaksi"),
                            resultSet.getBigDecimal("JumlahUang"),
                            resultSet.getString("Keterangan")
                    };
                    model.addRow(row);
                }
                DetailTransaksi.setModel(model);
            }
        }
        
        String query2 = "SELECT Transaksi.*, Siswa.Nama AS NamaSiswa FROM Transaksi " +
                 "JOIN Siswa ON Transaksi.NIS = Siswa.NIS " +
                 "WHERE Transaksi.NomorTransaksi = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query2)) {
            preparedStatement.setInt(1, nomorTransaksi);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    Date tanggal = resultSet.getDate("TanggalBayar");
                    DetailTransaksi.setNama(resultSet.getString("NamaSiswa"));
                    DetailTransaksi.setPembayar(resultSet.getString("Pembayar"));                    
                    DetailTransaksi.setPenerima(resultSet.getString("Penerima"));
                    DetailTransaksi.setTanggal(tanggal);

                    // Set other details as needed
                }
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Handle SQL exception (e.g., display an error message)
    }
}


    
    private void deleteSiswaFromDatabase(String nis) {
    try (Connection connection = DriverManager.getConnection(JDBC_URL, USER, PASSWORD)) {
        String deleteOrangTuaQuery = "DELETE FROM OrangTua WHERE NIS = ?";
        try (PreparedStatement deleteOrangTuaStatement = connection.prepareStatement(deleteOrangTuaQuery)) {
            deleteOrangTuaStatement.setString(1, nis);
            deleteOrangTuaStatement.executeUpdate();
        }
        
        String deleteKeteranganQuery = "DELETE FROM KeteranganTransaksi WHERE NomorTransaksi IN (SELECT NomorTransaksi FROM Transaksi WHERE NIS = ?)";
        try (PreparedStatement deleteKeteranganStatement = connection.prepareStatement(deleteKeteranganQuery)) {
            deleteKeteranganStatement.setString(1, nis);
            deleteKeteranganStatement.executeUpdate();
        }
        
        String deleteTransaksiQuery = "DELETE FROM Transaksi WHERE NIS = ?";
        try (PreparedStatement deleteTransaksiStatement = connection.prepareStatement(deleteTransaksiQuery)) {
            deleteTransaksiStatement.setString(1, nis);
            deleteTransaksiStatement.executeUpdate();
        }
        
        String deleteQuery = "DELETE FROM Siswa WHERE NIS = ?";
        try (PreparedStatement deleteStatement = connection.prepareStatement(deleteQuery)) {
            deleteStatement.setString(1,nis);
            int affectedRows = deleteStatement.executeUpdate();
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this,"Baris dihapus dari database.");
            } else {
                JOptionPane.showMessageDialog(this,"Gagal menghapus baris dari database atau baris tidak ditemukan.");
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Handle SQL exception (e.g., display an error message)
    }
}
    
    private void deleteOrangTuaFromDatabase(int id) {
    try (Connection connection = DriverManager.getConnection(JDBC_URL, USER, PASSWORD)) {
        String deleteOrangTuaQuery = "DELETE FROM OrangTua WHERE ID = ?";
        try (PreparedStatement deleteOrangTuaStatement = connection.prepareStatement(deleteOrangTuaQuery)) {
            deleteOrangTuaStatement.setInt(1, id);
            int affectedRows = deleteOrangTuaStatement.executeUpdate();
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this,"Baris dihapus dari database.");
            } else {
                JOptionPane.showMessageDialog(this,"Gagal menghapus baris dari database atau baris tidak ditemukan.");
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Handle SQL exception (e.g., display an error message)
    }
}
    
    private void deleteTransaksiFromDatabase(int nomorTransaksi) {
    try (Connection connection = DriverManager.getConnection(JDBC_URL, USER, PASSWORD)) {
        String deleteKeteranganQuery = "DELETE FROM KeteranganTransaksi WHERE NomorTransaksi = ?";
        try (PreparedStatement deleteKeteranganStatement = connection.prepareStatement(deleteKeteranganQuery)) {
            deleteKeteranganStatement.setInt(1, nomorTransaksi);
            deleteKeteranganStatement.executeUpdate();
        }
        
        String deleteTransaksiQuery = "DELETE FROM Transaksi WHERE NomorTransaksi = ?";
        try (PreparedStatement deleteTransaksiStatement = connection.prepareStatement(deleteTransaksiQuery)) {
            deleteTransaksiStatement.setInt(1, nomorTransaksi);
            int affectedRows = deleteTransaksiStatement.executeUpdate();
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this,"Baris dihapus dari database.");
            } else {
                JOptionPane.showMessageDialog(this,"Gagal menghapus baris dari database atau baris tidak ditemukan.");
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Handle SQL exception (e.g., display an error message)
    }
}
    
    private void fetchDataFromSiswaAndDisplayInEditFrame(String nis) {
    try (Connection connection = DriverManager.getConnection(JDBC_URL, USER, PASSWORD)) {
        String query = "SELECT * FROM Siswa WHERE NIS = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setString(1, nis);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    Date tanggalLahir = resultSet.getDate("TanggalLahir");
                    // Assuming DetailFrame has methods to set all the data
                    EditSiswa.setNIS(resultSet.getString("NIS"));
                    EditSiswa.setNama(resultSet.getString("Nama"));
                    EditSiswa.setGender(resultSet.getString("Gender"));
                    EditSiswa.setTempat(resultSet.getString("Tempat"));
                    EditSiswa.setTanggalLahir(tanggalLahir);
                    EditSiswa.setAlamat(resultSet.getString("Alamat"));
                    EditSiswa.setNoTelp(resultSet.getString("noTelp"));
                    // Set other details as needed
                }
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Handle SQL exception (e.g., display an error message)
    }
}
    
    private void fetchDataFromOrtuAndDisplayInEditFrame(int id) {
    try (Connection connection = DriverManager.getConnection(JDBC_URL, USER, PASSWORD)) {
        String query = "SELECT OrangTua.*, Siswa.Nama AS NamaSiswa " +
               "FROM OrangTua " +
               "JOIN Siswa ON OrangTua.NIS = Siswa.NIS " +
               "WHERE OrangTua.ID = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setInt(1, id);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    EditOrtu.setId(resultSet.getInt("ID"));
                    EditOrtu.setNamaAyah(resultSet.getString("NamaAyah"));                    
                    EditOrtu.setKerjaAyah(resultSet.getString("KerjaAyah"));
                    EditOrtu.setNamaIbu(resultSet.getString("NamaIbu"));
                    EditOrtu.setKerjaIbu(resultSet.getString("KerjaIbu"));
                    EditOrtu.setNamaSiswa(resultSet.getString("NamaSiswa"));

                }
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Handle SQL exception (e.g., display an error message)
    }
}
     
    public static void main(String args[]) {
    /* Set look and feel, other UI configurations */

    Dewantara frame = new Dewantara();
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            frame.setVisible(true); // Menampilkan GUI
        }
    });
    
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton refresh;
    private javax.swing.JTextField search;
    private javax.swing.JTable table;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
